package com.codemeet.entity;

public enum NotificationType {
    FRIENDSHIP_REQUEST,
    FRIENDSHIP_ACCEPTED,
    MEMBERSHIP_REQUEST,
    MEMBERSHIP_ACCEPTED,
    MEETING_SCHEDULED,
    MEETING_STARTED,
    PEER_MESSAGE,
    ROOM_MESSAGE,
    TEST
}
